services:
  - type: web
    name: json-mqtt-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    routes:
      - "/"

  - type: worker
    name: json-mqtt-worker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python mqtt_client.py
